POST http://localhost:3000/contact HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijg4NzJhNzc3LWViYWQtNGIxYS05NjI5LWM3MDc5NzEyNTQ3YiIsImlhdCI6MTc0ODkxNTMyMiwiZXhwIjoxNzQ5MDAxNzIyfQ.JLFytxUzzztP0-xPKAyOb4Digo93vtOU2pDf5LzWV6w
content-type: application/json

{
    "name": "Viviane",
    "email": "viviane@email.com",
    "phone": "88993553132",
    "company": "Acme",
    "status": "lead",
    "tag": "family"
}
