GET http://localhost:3000/contact/tags HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijg4NzJhNzc3LWViYWQtNGIxYS05NjI5LWM3MDc5NzEyNTQ3YiIsImlhdCI6MTc0ODkxNTMyMiwiZXhwIjoxNzQ5MDAxNzIyfQ.JLFytxUzzztP0-xPKAyOb4Digo93vtOU2pDf5LzWV6w
